name: Create Azure Resources

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resources using Bicep
      run: |
        az deployment group create --resource-group ${{ vars.AZURE_RG }} --template-file ./config/main.bicep --parameters namePrefix=${{ vars.AZURE_PREFIX }}
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
